networks:
  default:

services:
  db:
    image: mysql:8.0.32
    container_name: car_dealership_db
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: car_dealership_db
    restart:
      always

